### ISSUE TITLE
2.0.0 compatibility

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/Orleans.Providers.MongoDB#43]
The following error message was observed in a project that referenced the following packages: 
Microsoft.Orleans, 2.0.0
Orleans.Providers.MongoDB, 2.0.0-rc6

Do we need to release a new version that is compatible with Orleans 2.0.0? 

````
-		InnerException	{System.MissingMethodException: Method not found: 'System.Guid Orleans.Configuration.ClusterOptions.get_ServiceId()'.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo.<InjectDependencies>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Silo.<StartAsyncTaskWithPerfAnalysis>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Silo.<OnRuntimeServicesStart>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.LifecycleSubject.<WrapExecution>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.LifecycleSubject.<OnStart>d__4.MoveNext()}	System.Exception {System.MissingMethodException}
```

**Comment by bboyle1234** [comment]
Hmm, looks like this has already been done in code ... are we waiting on a release to nuget? 

![image](https://user-images.githubusercontent.com/1445862/38227192-15ee975a-36cb-11e8-863c-6a5cf302bec7.png)

**Comment by SebastianStehle** [comment]
I can make the release this afternoon. Its 9 am here. I was short in time due public holiday.

**Comment by bboyle1234** [comment]
@SebastianStehle  Fantastic, thank you.
