### ISSUE TITLE
MongoBulkWriteException Orleans.OrleansStatisticsTable index: _id_ dup key: { : "XXX" }

### ISSUE THREAD

**Issue by AwsomeCode** [OrleansContrib/Orleans.Providers.MongoDB#5]
Hi I am getting below exception

Error: 0 : [2017-04-14 09:15:28.080 GMT    50	ERROR  	100835	ClientLogStatistics	192.168.3.99:0]	!!!!!!!!!! Exception occurred during Stats reporter.	
Exc level 0: MongoDB.Driver.MongoBulkWriteException`1[MongoDB.Bson.BsonDocument]: A bulk write operation resulted in one or more errors.
  E11000 duplicate key error collection: Orleans.OrleansStatisticsTable index: _id_ dup key: { : "*cli/1966f180:229855227" }
   at MongoDB.Driver.MongoCollectionImpl`1.<BulkWriteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.MongoDB.Statistics.Repository.MongoStatisticsPublisherRepository.<InsertStatisticsCountersAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.MongoDB.Statistics.MongoStatisticsPublisher.<ReportStats>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Orleans.Runtime.LogStatistics.<DumpCounters>d__10.MoveNext()

**Comment by laredoza** [comment]
Hi,
Thanks for reporting this issue. I will post a fix soon.  I must admit that I wrote the basic stats implementation and haven't  had a chance to test it at all yet. 

I've got a bit of time this weekend and will finalize it.

**Comment by AwsomeCode** [comment]
@laredoza Thanks :)

**Comment by laredoza** [comment]
@AwsomeCode I've posted a fix. Should work now.

 I'd also suggest setting WriteLogStatisticsToTable="false", from what I've read this shouldn't be used on a production system. 

I will also double check the logged values against the SqlProvider version this weekend. I'll post another update once I'm done.

**Comment by AwsomeCode** [comment]
@laredoza Thank you for the quick fix 👍

**Comment by laredoza** [comment]
@AwsomeCode  No problem.  I suspect I"m the only one using this at the moment,  so your feedback would is appreciated.

**Comment by AwsomeCode** [comment]
@laredoza Ya I feel same, people don't use Mongodb much in Orleans. I don't see any drawback for using it.
Are you using mongodb for StorageProvider?

**Comment by laredoza** [comment]
@AwsomeCode I'm not sure why, I've had brilliant results using Mongo and Orleans. We've shaved off months of processing time by moving from Oracle to Mongo / Orleans (Went down from 4 months to 12 days, and that was if we didn't crash Oracle with the volume of data being imported). Having replication was awesome as well.

I haven't used the Mongo StorageProvider yet.

**Comment by laredoza** [comment]
@AwsomeCode  I created a package, install-package Orleans.Providers.MongoDB

**Comment by AwsomeCode** [comment]
Cool 👍
